### ISSUE TITLE
apache plugin template fails to parse

### ISSUE THREAD

**Issue by blkperl** [signalfx/puppet_collectd#49]
I copied the example from https://github.com/signalfx/puppet_collectd#class-collectdpluginapache and got a puppet error.

```
 Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template collectd/plugins/apache/10-apache.conf.erb:
```

**Comment by dgriff-tools** [comment]
Hi blkperl,

What is your puppet version and the puppet_collectd module version you have installed?

**Comment by blkperl** [comment]
Hi @dgriff-tools

We're using the following verions

signalfx-collectd (v0.1.10)
Puppet 4.8.1 (Centos 7)

## test.pp

```
class { 'collectd' :
    signalfx_api_token  => 'YOUR_SIGNALFX_API_TOKEN'
}

class { 'collectd::plugins::apache':
  modules => {
    'myinstance' => {
        'URL' => '"http://localhost/mod_status?auto"',
    }
  }
}
```

## puppet apply

```
[root@ collectd]# /opt/puppetlabs/bin/puppet apply test.pp --noop
Getting AWS metadata...
Getting AWS metadata...
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugins/apache.pp", 10]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugins/plugin_common.pp", 10]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template collectd/plugins/apache/10-apache.conf.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/collectd/templates/plugins/apache/10-apache.conf.erb
  Line: 4
  Detail: undefined method `each' for nil:NilClass
 at /etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugins/plugin_common.pp:27:16  at /etc/puppetlabs/code/environments/production/modules/collectd/manifests/plugins/apache.pp:14 on node redacted
```

**Comment by dgriff-tools** [comment]
Thanks @blkperl for the information.
